# This workflow configures the user-statistician with the
# dark color theme, but otherwise uses all of
# the defaults. It is configured on a daily schedule at 3am.

name: user-statistician

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ main, master ]
    paths: [ '.github/workflows/user-stats.yml' ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Generate the user stats image
        uses: cicirello/user-statistician@d1918dd362c46c2dc1788139947224eee4fef0b8 # v1
        with:
          colors: dark
          hide-keys: repositories, featured, followers, following, sponsors, sponsoring, reviews, contribTo
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
